### ISSUE TITLE
Cross-compile in OpenEmbedded requires autogen.sh hack

### ISSUE THREAD

**Issue by bkauler** [masneyb/gftp#106]
Just to let you know, I had to do a little hack to get the latest gftp (2021-04-07) to compile in OpenEmbedded.

OE is a cross-compile environment, that I use to compile packages for EasyOS, see latest release announcement if interested: 
https://bkhome.org/news/202104/easyos-dunfell-version-27-released.html

In OE, autogen.sh fails, and I have to pre-create two files. This is the function in the gftp recipe, that runs before running autogen.sh:

#autogen.sh fail, hack...
do_configure_prepend() {
 mkdir -p ${S}/autoconf-m4
 mkdir -p ${S}/autoconf
 touch ${S}/autoconf/config.rpath
}

Previously, I was using 2.6.0b, September 2020, and had to do this:

#20200921 autogen.sh reports this file missing. hack...
do_configure_prepend() {
 touch ${S}/config.rpath
}

Note, the reason that I am updating is because 2.6.0b is broken. When connect to a new ssh2 site, there is supposed to be a popup asking to confirm yes/no this new ssh2 key, but that doesn't popup. So no way to confirm yes.

I will test the latest, and will raise that as a separate issue if still have that bug.

**Comment by wdlkmpx** [comment]
Those dirs should be automatically created by the autotools apps, but something is going on.

`autoreconf -vi` should work, but I know it doesn't always work, that's why autogen.sh fixes possible issues before running the apps in the correct order.

autogen.sh now pre creates autoconf, autoconf-m4, and config.rpath.
