### ISSUE TITLE
Segmentation fault on connecting after bookmark change

### ISSUE THREAD

**Issue by MartinX3** [masneyb/gftp#117]
1. A bookmark with FTPS exist.
2. I try to connect to it.
3. Connection is not possible, because gFTP said, that the SSL support is not compiled in.
4. I edit the bookmark to use SSH2.
5. I try to connect to the bookmark.
6. Segmentation fault.

After the crash I can connect to the server.

**Comment by wdlkmpx** [comment]
![Screenshot(3)](https://user-images.githubusercontent.com/10052849/139488409-75e6365e-f5d4-4f1f-893a-a0e7a93c5d4e.png)

It's buggy or broken, but it seems to work with a local server, vsftpd. I guess it works under certain conditions, using legacy protocol communications with a specific encryption method. I'm just speculating since this stuff is uncharted territory

![Screenshot(2)](https://user-images.githubusercontent.com/10052849/139488422-ae5bc689-213d-449a-a44e-d8610591090c.png)
