### ISSUE TITLE
Port patches from https://github.com/fangq/gftp

### ISSUE THREAD

**Issue by wdlkmpx** [masneyb/gftp#14]
I can port patches from https://github.com/fangq/gftp if you are willing to merge them. For some reason git tells me  that both repos have unrelated histories so it has to be done manually.

The patches fix miscellaneous issues and improve the gui. It's worth mentioning that the current GtkCList stuff will never compile in gtk3+... it will be a lot of work to replace it with GtkTreeView or something [I'm not qualified], but some patches improve GtkCList stuff and make gftp more friendly.

I have already ported most of the patches,  I'll be testing.. I can open pull requests.

**Comment by masneyb** [comment]
Yes, I'm more than willing to merge improvements to gftp. Thank you for your work.

**Comment by wdlkmpx** [comment]
I see issues in the gtk2 ui

- No icons are displayed in the file list
- (gftp-gtk:30235): Gtk-CRITICAL **: IA__gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed
- (gftp-gtk:30235): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

A lot of g_object_unref warnings or errors, these are not caused by the fangq patches..  which are safe to merge (sort of).

Testing in debian stretch.

**Comment by wdlkmpx** [comment]
I no longer see glib errors. I ran `git bisect` to try to identify a regression, and somehow it fixed the glib warnings I was seeing. I'm not sure what was wrong.. I compiled and installed gftp several times before, I don't recall if I used prefix=/usr before, but I think I did.

For the patches I add, I take the time verify that gftp compiles without gtk warnings. I compile gftp for every change I make. Currently there are 7 PR with patches from the fengq repo,  I just tested and all of them compile fine and look mergeable.

Some other patches are a little big and add buttons and stuff.

**Comment by masneyb** [comment]
Thank you so much for your work.

If you're looking for some other easier cleanups, then I noticed that there's some GLIB_MAJOR_VERSION and GTK_MAJOR_VERSION version checks. All of the ones for version 1 can just be deleted.

I also suggest looking at the other #ifdef checks since I'm sure there's some checks for some ancient systems that are no longer in use that can be removed. It'll make the code simpler and easier to make changes in the future.

**Comment by wdlkmpx** [comment]
I don't often edit C code but I see deprecated stuff, and no warnings. Perhaps everything should be restarted and proper support for other systems than linux should be readded as needed. And no DOS or Windows support.

I see deprecated stuff but no warnings.
https://developer.gnome.org/gtk2/stable/GtkCombo.htm

```
....
gftp-gtk.c:  hostedit = gtk_combo_new ();
gftp-gtk.c:  gtk_combo_set_case_sensitive (GTK_COMBO (hostedit), 1);
gftp-gtk.c:    gtk_combo_set_popdown_strings (GTK_COMBO (hostedit), tmplistvar->list);
gftp-gtk.c:  gtk_combo_disable_activate (GTK_COMBO (hostedit));
gftp-gtk.c:  portedit = gtk_combo_new ();
gftp-gtk.c:  gtk_combo_set_case_sensitive (GTK_COMBO (portedit), 1);
gftp-gtk.c:    gtk_combo_set_popdown_strings (GTK_COMBO (portedit), tmplistvar->list);
gftp-gtk.c:  gtk_combo_disable_activate (GTK_COMBO (portedit));
gftp-gtk.c:  useredit = gtk_combo_new ();
gftp-gtk.c:  gtk_combo_set_case_sensitive (GTK_COMBO (useredit), 1);
gftp-gtk.c:    gtk_combo_set_popdown_strings (GTK_COMBO (useredit), tmplistvar->list);
gftp-gtk.c:  gtk_combo_disable_activate (GTK_COMBO (useredit));
gftp-gtk.c:  wdata->combo = gtk_combo_new ();
gftp-gtk.c:  gtk_combo_set_case_sensitive (GTK_COMBO (wdata->combo), 1);
gftp-gtk.c:    gtk_combo_set_popdown_strings (GTK_COMBO (wdata->combo), *wdata->history);
gftp-gtk.c:  gtk_combo_disable_activate (GTK_COMBO (wdata->combo));
misc-gtk.c:  gtk_combo_set_popdown_strings (GTK_COMBO (widget), *history);
...
```

It should trigger a warning msg like this:
WARNING: GtkCombo has been deprecated since version 2.4 and should not be used in newly-written code. Use GtkComboBox instead.

**Comment by masneyb** [comment]
Thanks again for your work. I think that I've merged everything you've sent so far. Here's a few ideas if you're looking for some other contributions:

- The automake/autoconf build system is old. I think Meson (https://mesonbuild.com/) is the new thing to use these days. Unfortunately, gftp's existing build setup doesn't work on my Fedora 31 system that I recently upgraded to. I believe that it worked on Fedora 30. (or maybe it was 29?)
- There's ifdef checks for HAVE_GETADDRINFO, USE_SSL, HAVE_IPV6, etc. It's 2020 and a lot of these I'd just remove since modern systems will have that stuff.
- Work on upgrading a deprecated widget one at a time to the recommended replacement.

**Comment by masneyb** [comment]
Also, gftp needs a new maintainer. Are you interested? I'd be glad to review your patches to get you going.

**Comment by wdlkmpx** [comment]
I'm not familiar with meson, but in the meantime I'll try to update, simplify and fix the autotools/autoconf stuff.. I'll try.

The project might need a team. I can perform tests, update gtk stuff a bit, nothing that requires a gtk guru, I can update po files and deal autotools stuff, I can produce release tarballs, but I'm not that qualified to update docs and stuff. I'd rather delete them.

So I think it's good to have "collaborators", or a team with write access to the git repo. A team member should be removed after a long period of inactivity... the key is in the web site.. gftp.org .. a link to this git repo will increase its visibility..

**Comment by wdlkmpx** [comment]
I just tried to build the gtk3 ui, tons of errors, many widgets no longer exist. An app that has been updated to gtk 2.24 is mostly compatible with gtk3.

There are a lot of deprecated widgets that are not available in gtk3. I guess it's possible to fix all of these issues, but it will take some time, and a team perhaps, and as far as I know the GtkCList -> GtkTreeView transition will be a bit traumatic.. requires a gtk guru.

The fangq patches improve GtkCList stuff (gtk1), making it respond to more events, but it also makes it more difficult to port it to GtkTreeView I guess... these are completely different widgets with unrelated functions.

I'm sure that are other similar challenges, but probably not as difficult.

**Comment by masneyb** [comment]
I just updated the www.gftp.org website to point to this git repository. 

Since gftp has a library for all backend and protocol-specific code, and two user interfaces (text and gtk), rename the exist src/gtk directory to src/gtk-deprecated and leave that old code as is. Create a new src/gtk directory and create a new modern user interface as you see fit. GTK now has Glade (https://glade.gnome.org/) to help build user interfaces. I'm not sure if this the new recommended approach but something to look into. Honestly, I think that'll be a whole lot easier than migrating all of the old GTK 1.2 code to version 3 since that's going to be a lot more work. A user interface builder like glade with remove a lot of the boiler plate code that's currently in the src/gtk directory so there will be a lot less code to maintain.

If you did that, I would be willing to go through and and help clean up the code in the lib/ directory.

Thank you for your good work that you've contributed so far.

**Comment by wdlkmpx** [comment]
reading a fengq patch that will be in a PR: "apply PRET patch submitted by Chris Droshalla for better handling of distributed sites" ..... I see that it doesn't edit gtk stuff, only a rfcxxx.c file... the gtk ui dynamically creates a checkbox to enable or disable that feature.

I'm not familiar with glade, I think it only creates static widgets..  I used it once to create a checkbox for a deadbeef player checkbox.. it still requires a deep understanding of gtk callbacks and stuff.. so GTK is not friendly in any way, shape or form. So either way it will take some time.

People are still writing how gtk3 has many regressions compared to gtk2. LXDE migrated to Qt,

I also want to update and help update other small projects that use a gtk ui, and this is how I document my journey.

I guess we agree that the current gtk stuff is a dead end, but I can be a temporary maintainer for the gtkui.,

Let's see how far I get with this, although I may become busy, but I'm setting the scene. I'm sure other people will find it easier to do things.

**Comment by wdlkmpx** [comment]
I think I ported all the essential patches. Closing this issue.

I'm trying to convert all the GtkItemFactory code to GtkUIManager, and it's the most complex challenge so far, I'm slowly fixing some of the many bugs the change introduces, but it's a big change, it's pushing my limits

I wonder if it's ok to remove some obscure features, etc if I'm not able to fix the issues..

**Comment by masneyb** [comment]
> I'm slowly fixing some of the many bugs the change introduces, but it's a big change, it's pushing my limits

Break up the bigger problem up into smaller, more manageable problems. :)

> I wonder if it's ok to remove some obscure features, etc if I'm not able to fix the issues..

Yes, I would consider changes like that.

Thank you for all of your good work so far. I hope to see more contributions from you.

**Comment by wdlkmpx** [comment]
Now I understand why both Local and Remote have the same menu items
and actions.. it's possible to connect to a remote host that becomes
the "Local" host.

I guess gFTP offers son advanced usage that most people don't know
about.. or may not understand.

So... it's an interesting situation that I never understood before. So
what happens if I try to download or upload files in this case? I
still don't know

So it's an interesting predicament

**Comment by masneyb** [comment]
> Now I understand why both Local and Remote have the same menu items
and actions.. it's possible to connect to a remote host that becomes
the "Local" host.

Yes.... so you can connect to a remote SFTP site on the left side and a remote FTP server on the right side. In that particular situation, the data will be transferred from the SFTP server over SSH, to your local machine, and back out to the FTP server.

Some FTP sites allow direct transfer. You can connect to two remote FTP sites, the control connection goes to your machine, but the data connection goes directly between the two FTP sites. There can some security implications with this since an attacker can connect to the listening side first and inject their own file so I believe that some FTP servers disable this feature. In that case, gftp should fall back to sending the file to your local computer first, and then back out to the other site.
